image: debian:latest

before_script:
  - apt update
  - apt install -y build-essential

stages:
  - compile
  - doc

compile:
  stage: compile
  script:
    - make

pages:
  stage: doc
  script:
    - apt update
    - apt install -y doxygen graphviz
    - make doc
  artifacts:
    paths:
      - public
