#include "string.h"
#include "userspace_apps.h"
#include "hash.h"
#include "debug.h"
#include "errno.h"

/**
 * Mapping from symbol to symbol table ptr.
 */
hash_t symbol_to_uapp;

void uapp_init()
{
    hash_init_string(&symbol_to_uapp);
    // The symbol table is automatically generated by
    // a script. We need to initialize the hash table ourselves however.
    struct uapps *current = (struct uapps *)symbols_table;
    while (current->name) {
        hash_set(&symbol_to_uapp, (void *)current->name, current);
        current++;
    }
}

struct uapps *get_uapp_by_name(const char *name)
{
    struct uapps *uapp = hash_get(&symbol_to_uapp, (void *)name, NULL);
    if (uapp == NULL) {
        return ERR_PTR(-EINVAL);
    }

    return uapp;
}